
project_id = "lhvuoorzmjjnaasahmyw"
org_id = "41269622"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "https://fund-road.com"
additional_redirect_urls = ["https://fund-road.com"]
jwt_expiry = 3600
enable_signup = true
enable_refresh_token_rotation = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.sms]
enable_signup = true
enable_confirmations = true

[functions]
[functions.translate-content]
verify_jwt = true
[functions.check-deepl-key]
verify_jwt = true
[functions.send-email-verification]
verify_jwt = false

[realtime]
[realtime.prod_wal]
enabled = true
