
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lhvuoorzmjjnaasahmyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxodnVvb3J6bWpqbmFhc2FobXl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NDIwMjMsImV4cCI6MjA1OTUxODAyM30.-tqImetLaIFhLey-JrWgiCLOOdYMNsc2FSXIt-ey1ds";

// Log configuration details in development to help with debugging
if (process.env.NODE_ENV !== 'production') {
  console.log('Supabase Client Configuration:');
  console.log(`- URL: ${SUPABASE_URL}`);
  console.log(`- Key: ${SUPABASE_PUBLISHABLE_KEY.substring(0, 10)}...`);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
